LANGUAGE_SKILLS_THRESHOLD = 0.1
IT_SKILLS_THRESHOLD = 0.1
PROFESSIONAL_SKILLS_THRESHOLD = 0.1
SOFT_SKILLS_THRESHOLD = 0.1

DEFAULT_MAX_NUMBER_OF_SKILLS_FOR_GPT = 50
THRESHOLD_STEP = 0.01

DEFAULT_SKILL_TYPE_PROFESSIONAL = "Professional"
DEFAULT_SKILL_TYPE_IT = "IT"
DEFAULT_SKILL_TYPE_SOFT = "Soft"
DEFAULT_SKILL_TYPE_LANGUAGE = "Language"

DEFAULT_THRESHOLD_FOR_CREATING_NEW_SKILLS = 0.9

NUM_SIMILAR_SKILLS_FOR_COURSE_CONNECTION = 100
NUM_SIMILAR_SKILLS_FOR_PROFESSION_CONNECTION = 100
DISPLAY_SIMILAR_SKILLS_LIMIT = 10  # NEXT TO NEW SKILL

BATCH_SIZE = 500  # LOADING FROM FILE

skill_type_threshold = {
    DEFAULT_SKILL_TYPE_PROFESSIONAL: LANGUAGE_SKILLS_THRESHOLD,
    DEFAULT_SKILL_TYPE_IT: IT_SKILLS_THRESHOLD,
    DEFAULT_SKILL_TYPE_SOFT: SOFT_SKILLS_THRESHOLD,
    DEFAULT_SKILL_TYPE_LANGUAGE: LANGUAGE_SKILLS_THRESHOLD
}

path_data = {
    DEFAULT_SKILL_TYPE_LANGUAGE: (
        'data1/Language_embeddings.npy', 'data1/processed_Language_lines.npy', 'data1/title_Language_lines.npy'),
    DEFAULT_SKILL_TYPE_IT: ('data1/IT_embeddings.npy', 'data1/processed_IT_lines.npy', 'data1/title_IT_lines.npy'),
    DEFAULT_SKILL_TYPE_PROFESSIONAL: (
        'data1/Professional_embeddings.npy', 'data1/processed_Professional_lines.npy',
        'data1/itle_Professional_lines.npy'),
    DEFAULT_SKILL_TYPE_SOFT: (
        'data1/Soft_embeddings.npy', 'data1/processed_Soft_lines.npy', 'data1/title_Soft_lines.npy'),
    # 'Courses': ('data1/Course_embeddings', 'data1/processed_Course_lines.npy', 'data1/title_Course_lines.npy'),
    # 'Professions': ('data1/Professions_embeddings.npy', 'data1/processed_Professions_lines.npy', 'data1/title_Professions_lines.npy'),
}

DEFAULT_NEW_SKILL_LABEL = "New_TN1"
DEFAULT_SKILL_LABEL = "Original_TN1"
DEFAULT_PROFESSION_LABEL = "Profession_TEST_N"
DEFAULT_PERSON_LABEL = "Client_N"
DEFAULT_COURSE_LABEL = "Program_TN"

MENU_ITEMS = {
    "English": {
        "name": "Name",
        "add_course_button": "Add Course",
        "new_skills": "New Skills",
        "skills_similar_to": "Skills similar to ",
        "skill_updated": "Skill updated",
        "accept_new_skill": "Accept new skill and make its label Original",
        "generate_gpt_desc_en": "Generate Description in English with GPT",
        "generate_gpt_desc_fi": "Generate Description in Finnish with GPT",
        "skills": "Skills",
        "courses": "Courses",
        "professions": "Professions",
        "persons": "Persons",
        "add_skill": "Add Skill",
        "delete_skill": "Delete Skill",
        "update_skill": "Update Skill",
        "view_related_nodes": "View Related Nodes",
        "view_new_skills": "View New Skills",
        "node_label": "Node Label",
        "node_title": "Node Title",
        "node_description": "Node Description",
        "relationship_type": "Relationship Type",
        "menu": "Menu",
        "skill_management": "Skill Management",
        "related_nodes": "Related Nodes",
        "success_add_skill": "Skill '{skill_title}' added successfully.",
        "success_delete_skill": "Skill '{skill_title}' deleted successfully.",
        "success_update_skill": "Skill '{skill_title}' updated successfully.",
        "view": "View",
        "select": "Select",
        "add": "Add",
        "load_from_file": "Load from File",
        "success_load_skills": "Skills loaded from file successfully.",
        "select_skill_for_delete": "Select Skill for Delete",
        "select_skill_for_update": "Select Skill for Update",
        "edit_fields": "Edit Fields",
        "select_skill": "Select Skill",
        "related_programs_or_professions": "Related Programs or Professions",
        "related_courses": "Related Courses",
        "related_professions": "Related Professions",
        "related_persons": "Related Persons",
        "add_course": "Add Course",
        "delete_course": "Delete Course",
        "update_course": "Update Course",
        "success_add_course": "Course '{course_title}' added successfully.",
        "success_delete_course": "Course '{course_title}' deleted successfully.",
        "success_update_course": "Course '{course_title}' updated successfully.",
        "select_course": "Select Course",
        "select_course_for_update": "Select Course for Update",
        "no_courses_available": "No courses available to update.",
        "related_skills": "Related Skills",
        "disconnect": "Disconnect",
        "from": "from",
        "skill_name": "Skill Name",
        "skill_description": "Skill Description",
        "profession_name": "Profession Name",
        "profession_description": "Profession Description",
        "person_name": "Person Name",
        "labels": "Labels",
        "related_new_skills": "Related New Skills",
        "add_profession": "Add Profession",
        "delete_profession": "Delete Profession",
        "update_profession": "Update Profession",
        "success_add_profession": "Profession '{profession_title}' added successfully.",
        "success_delete_profession": "Profession '{profession_title}' deleted successfully.",
        "success_update_profession": "Profession '{profession_title}' updated successfully.",
        "select_profession": "Select Profession",
        "select_profession_for_update": "Select Profession for Update",
        "no_professions_available": "No professions available to update.",
        "add_person": "Add Person",
        "delete_person": "Delete Person",
        "update_person": "Update Person",
        "success_add_person": "Person '{person_name}' added successfully.",
        "success_delete_person": "Person '{person_name}' deleted successfully.",
        "success_update_person": "Person '{person_name}' updated successfully.",
        "select_person": "Select Person",
        "select_person_for_update": "Select Person for Update",
        "no_persons_available": "No persons available to update.",
        "connect_to_existing_skills": "Connect to Existing Skills",
        "connect_to_existing_courses": "Connect to Existing Courses",
        "select_skills": "Select Skills",
        "connect_skills": "Connect Skills",
        "success_connect_skills_to_person": "Skills successfully connected to person.",
        "success_connect_skills_to_course": "Skills successfully connected to course.",
        "suggest_training_program": "Suggest Training Program",
        "select_client_for_suggestion": "Select Client for Suggestion",
        "select_profession_for_suggestion": "Select Profession for Suggestion",
        "title_empty_warning": "Skill title cannot be empty!",
        "connected_skills": "Connected Skills",
        "unconnected_skills": "Unconnected Skills",
        "disconnect_skill": "Disconnect Skill",
        "connect_skill": "Connect Skill",
        "success_disconnect_skills_from_course": "Skills successfully disconnected from course '{course_title}'.",
        "connected_skills_multiselect": "Connected Skills",
        "unconnected_skills_multiselect": "Unconnected Skills",
        "disconnect_skill_button": "Disconnect",
        "connect_skill_button": "Connect",
        "select_profession_for_connect": "Select Profession for Connect",
        "success_connect_skills_to_profession": "Skills successfully connected to profession.",
        "person_exists": "Person '{name}' already exists in the graph.",
        "skill_not_found": "Skill '{skill_title}' not found.",
        "person_added_success": "Person '{name}' added successfully.",
        "person_not_exist": "Person '{person_name}' does not exist.",
        "person_connected_to_skills": "Person '{person_name}' connected to skills successfully.",
        "person_not_exist_in_graph": "Person '{name}' does not exist in the graph.",
        "person_deleted": "Person '{name}' deleted from the graph.",
        "person_updated": "Person '{name}' updated.",
        "select_skills_for_person": "Select Skills for Person",
        "add_person_with_selected_skills_to_the_graph": "Add Person with Selected Skills to the Graph",
        "person_name_empty_warning": "Person name cannot be empty!",
        "person_has_skills": "Person has the following skills:",
        "person_has_no_skills": "Person has no following skills:",
        "edit_name": "Edit Name",
        "skills_not_acquired_by_client": "Skills for {selected_profession} not yet acquired by {selected_client_name}:",
        "courses_to_acquire_skills": "Courses to acquire missing skills:",
        "no_programs_for_missing_skills": "No programs available for the missing skills.",
        "all_skills_acquired": "{client_name} has already acquired all skills for {profession_title}.",
        "client_skills_programs_graph": "Client-Skills-Programs Graph",
        "success_disconnect_person_from_course": "Skill successfully disconnected from person.",
        "needed_skills": "Needed Skills:",
        "load_course_from_file": "Load Course from File",
        "view_related_skills": "View Related Skills",
        "connect_to_skills": "Connect to Skills",
        "success_disconnect_skills_from_profession": "Skills successfully disconnected from profession.",
        "select_profession_to_connect_skills": "Select profession to connect skills.",
        "remove_connection_between": "Remove connection between: ",
        "and": "and",
        "persons_skills": "Person's Skills",
        "no_related_nodes": "No related nodes found.",

    },
    "Finnish":
        {
            "persons_skills": "Henkilön taidot",
            "no_related_nodes": "Ei liittyviä solmuja löydetty.",

            "load_course_from_file": "Lataa kurssi tiedostosta",
            "remove_connection_between": "Poista yhteys välillä: ",
            "and": "ja",
            "success_disconnect_skills_from_profession": "Taidot onnistuneesti katkaistu ammatista.",
            "view_related_skills": "Näytä liittyvät taidot",
            "connect_to_skills": "Yhdistä taitoihin",
            "no_profession_available": "Ei ammattia saatavilla.",
            "select_profession_to_connect_skills": "Valitse ammatti yhdistettäväksi taitoihin.",
            "needed_skills": "Tarvittavat taidot:",
            "success_disconnect_person_from_course": "Taito onnistuneesti katkaistu henkilöltä.",
            "name": "Nimi",
            "client_skills_programs_graph": "Asiakkaan taidot - ohjelmat kaavio",
            "all_skills_acquired": "{client_name} on jo hankkinut kaikki taidot {profession_title}.",
            "no_programs_for_missing_skills": "Ei kuursia saatavilla puuttuville taidoille.",
            "courses_to_acquire_skills": "Kurssit puuttuvien taitojen hankkimiseksi:",
            "skills_not_acquired_by_client": "Taidot {selected_profession} joita {selected_client_name} ei ole vielä hankkinut:",
            "person_has_skills": "Henkilöllä on seuraavat taidot:",
            "person_has_no_skills": "Henkilöllä ei ole seuravia taitoja:",
            "edit_name": "Muokkaa nimeä",
            "select_skills_for_person": "Valitse taidot henkilölle",
            "add_person_with_selected_skills_to_the_graph": "Lisää henkilö valituilla taidoilla graafiin",
            "person_name_empty_warning": "Henkilön nimi ei voi olla tyhjä!",
            "person_exists": "Henkilö '{name}' on jo olemassa graafissa.",
            "skill_not_found": "Taitoa '{skill_title}' ei löydy.",
            "person_added_success": "Henkilö '{name}' lisätty onnistuneesti.",
            "person_not_exist": "Henkilö '{person_name}' ei ole olemassa.",
            "person_connected_to_skills": "Henkilö '{person_name}' yhdistetty taitoihin onnistuneesti.",
            "person_not_exist_in_graph": "Henkilö '{name}' ei ole olemassa graafissa.",
            "person_deleted": "Henkilö '{name}' poistettu graafista.",
            "person_updated": "Henkilö '{name}' päivitetty.",
            "success_connect_skills_to_profession": "Taidot yhdistetty onnistuneesti ammattiin.",
            "select_profession_for_connect": "Valitse Ammatti Yhdistettäväksi",
            "add_course_button": "Lisää kurssi",
            "new_skills": "Uudet taidot",
            "skill_updated": "Taito hyväksytty",
            "skills_similar_to": "Taidot, jotka ovat samanlaisia kuin",
            "accept_new_skill": "Hyväksy uusi taito ja merkitse sen labeliksi Alkuperäinen",
            "generate_gpt_desc_en": "Generoi kuvaus englanniksi (GPT)",
            "generate_gpt_desc_fi": "Generoi kuvaus suomeksi (GPT)",
            "skills": "Taidot",
            "courses": "Kurssit",
            "professions": "Ammatit",
            "persons": "Henkilöt",
            "add_skill": "Lisää taito",
            "delete_skill": "Poista taito",
            "update_skill": "Päivitä taito",
            "view_related_nodes": "Näytä liittyvät solmut",
            "view_new_skills": "Näytä uudet taidot",
            "node_label": "Solmun tunniste",
            "node_title": "Solmun nimi",
            "node_description": "Solmun kuvaus",
            "relationship_type": "Suhdetyyppi",
            "menu": "Valikko",
            "skill_management": "Taitojen hallinta",
            "related_nodes": "Liittyvät solmut",
            "success_add_skill": "Taito '{skill_title}' lisätty onnistuneesti.",
            "success_delete_skill": "Taito '{skill_title}' poistettu onnistuneesti.",
            "success_update_skill": "Taito '{skill_title}' päivitetty onnistuneesti.",
            "view": "Näytä",
            "select": "Valitse",
            "add": "Lisää",
            "load_from_file": "Lataa tiedostosta",
            "success_load_skills": "Taidot ladattu tiedostosta onnistuneesti.",
            "select_skill_for_delete": "Valitse taito poistettavaksi",
            "select_skill_for_update": "Valitse taito päivitettäväksi",
            "edit_fields": "Muokkaa kenttiä",
            "select_skill": "Valitse taito",
            "related_programs_or_professions": "Liittyvät ohjelmat tai ammatit",
            "related_courses": "Liittyvät kurssit",
            "related_professions": "Liittyvät ammatit",
            "related_persons": "Liittyvät henkilöt",
            "add_course": "Lisää kurssi",
            "delete_course": "Poista kurssi",
            "update_course": "Päivitä kurssi",
            "success_add_course": "Kurssi '{course_title}' lisätty onnistuneesti.",
            "success_delete_course": "Kurssi '{course_title}' poistettu onnistuneesti.",
            "success_update_course": "Kurssi '{course_title}' päivitetty onnistuneesti.",
            "select_course": "Valitse kurssi",
            "select_course_for_update": "Valitse kurssi päivitettäväksi",
            "no_courses_available": "Ei kursseja päivitettäväksi.",
            "related_skills": "Liittyvät taidot",
            "disconnect": "Katkaise yhteys",
            "from": "kohteesta",
            "skill_name": "Taidon nimi",
            "skill_description": "Taidon kuvaus",
            "profession_name": "Ammatin nimi",
            "profession_description": "Ammatin kuvaus",
            "person_name": "Henkilön nimi",
            "labels": "Tunnisteet",
            "related_new_skills": "Liittyvät Uudet Taidot",
            "add_profession": "Lisää ammatti",
            "delete_profession": "Poista ammatti",
            "update_profession": "Päivitä ammatti",
            "success_add_profession": "Ammatti '{profession_title}' lisätty onnistuneesti.",
            "success_delete_profession": "Ammatti '{profession_title}' poistettu onnistuneesti.",
            "success_update_profession": "Ammatti '{profession_title}' päivitetty onnistuneesti.",
            "select_profession": "Valitse ammatti",
            "select_profession_for_update": "Valitse ammatti päivitettäväksi",
            "no_professions_available": "Ei ammatteja päivitettäväksi.",
            "add_person": "Lisää henkilö",
            "delete_person": "Poista henkilö",
            "update_person": "Päivitä henkilö",
            "success_add_person": "Henkilö '{person_name}' lisätty onnistuneesti.",
            "success_delete_person": "Henkilö '{person_name}' poistettu onnistuneesti.",
            "success_update_person": "Henkilö '{person_name}' päivitetty onnistuneesti.",
            "select_person": "Valitse henkilö",
            "select_person_for_update": "Valitse henkilö päivitettäväksi",
            "no_persons_available": "Ei henkilöitä päivitettäväksi.",
            "connect_to_existing_skills": "Yhdistä olemassa oleviin taitoihin",
            "connect_to_existing_courses": "Yhdistä olemassa oleviin kursseihin",
            "select_skills": "Valitse taidot",
            "connect_skills": "Yhdistä taidot",
            "success_connect_skills_to_person": "Taidot yhdistetty onnistuneesti henkilöön.",
            "success_connect_skills_to_course": "Taidot yhdistetty onnistuneesti kurssiin.",
            "suggest_training_program": "Ehdota koulutusohjelmaa",
            "select_client_for_suggestion": "Valitse asiakas ehdotusta varten",
            "select_profession_for_suggestion": "Valitse ammatti ehdotusta varten",
            "title_empty_warning": "Taidon nimi ei voi olla tyhjä!",
            "connected_skills": "Liitetyt taidot",
            "unconnected_skills": "Liittämättömät taidot",
            "disconnect_skill": "Katkaise taito",
            "connect_skill": "Yhdistä taito",
            "success_disconnect_skills_from_course": "Taidot on onnistuneesti katkaistu kurssista '{course_title}'.",
            "connected_skills_multiselect": "Liitetyt taidot",
            "unconnected_skills_multiselect": "Liittämättömät taidot",
            "disconnect_skill_button": "Katkaise",
            "connect_skill_button": "Yhdistä",
        }
}

NODE_PROPERTIES = {
    "skill": {
        "English": {
            "title": "Title",
            "description": "Description",
            "source_id": "Source ID",
            "source_code": "Source Code",
            "title_fi": "Title (FI)",
            "description_fi": "Description (FI)",
            "type": "Type"
        },
        "Finnish": {
            "title": "Taidon nimi",
            "description": "Taidon kuvaus",
            "source_id": "Lähde-ID",
            "source_code": "Lähdekoodi",
            "title_fi": "Nimi (FI)",
            "description_fi": "Kuvaus (FI)",
            "type": "Tyyppi"
        }
    },
    "course": {
        "English": {
            "title": "Title",
            "title_fi": "Title (FI)",
            "description": "Description",
            "description_fi": "Description (FI)",
            "source_code": "Source Code",
            "location": "Location",
            "skills": "Skills"
        },
        "Finnish": {
            "title": "Kurssin nimi",
            "title_fi": "Kurssin nimi (FI)",
            "description": "Kurssin kuvaus",
            "description_fi": "Kurssin kuvaus (FI)",
            "source_code": "Lähdekoodi",
            "location": "Sijainti",
            "skills": "Taidot"
        }
    },
    "profession": {
        "English": {
            "title": "Title",
            "description": "Description (EN)",
            "source_si": "Source SI",
            "source_id": "Source ID",
            "title_fi": "Title (FI)",
            "description_fi": "Description (FI)",
            "skills": "Required Skills"
        },
        "Finnish": {
            "title": "Ammatin nimi",
            "description": "Ammatin kuvaus",
            "source_si": "Lähde-SI",
            "source_id": "Lähde-ID",
            "title_en": "Nimi (EN)",
            "title_fi": "Nimi (FI)",
            "description_en": "Kuvaus (EN)",
            "description_fi": "Kuvaus (FI)",
            "skills": "Ammattitaitovaatimukset"
        }
    },
    "person": {
        "English": {
            "name": "Name"
        },
        "Finnish": {
            "name": "Nimi"
        }
    }
}
